export const LIKE_REQUEST = "LIKE_REQUEST";
export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const LIKE_FAILURE = "LIKE_FAILURE";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST";
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_FAIL = "ADD_COMMENT_FAIL";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";

export const MY_POST_REQUEST = "MY_POST_REQUEST";
export const MY_POST_SUCCESS = "MY_POST_SUCCESS";
export const MY_POST_FAILURE = "MY_POST_FAILURE";

export const NEW_POST_REQUEST = "NEW_POST_REQUEST"; 
export const NEW_POST_SUCCESS = "NEW_POST_SUCCESS";
export const NEW_POST_FAILURE = "NEW_POST_FAILURE";

export const UPDATE_CAPTION_REQUEST = "UPDATE_CAPTION_REQUEST"; 
export const UPDATE_CAPTION_SUCCESS = "UPDATE_CAPTION_REQUEST"; 
export const UPDATE_CAPTION_FAILURE = "UPDATE_CAPTION_REQUEST"; 

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST"; 
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS"; 
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE"; 

export const USER_POST_REQUEST = "USER_POST_REQUEST"; 
export const USER_POST_SUCCESS = "USER_POST_SUCCESS"; 
export const USER_POST_FAILURE = "USER_POST_FAILURE"; 

